mu = 1.3e+20
max_T = 1.33
ISP = 3872.0
TOF = 34713360.0
l_star = 149598023000
m_star = 3366.0
t_star = 5074778.662111725
g0 = 9.80665
env_step_size = 86400
max_episode_steps = 500
training_steps = 1_000
tb_log_name = "SAC_TBR_training"
env_type = "TwoBody_Orb2Orb_Transfer_Env_nd_obs5"
eval_freq = 1000
n_eval_episodes = 32
print_freq = 1_000
pre_train_networks = true
buffer_size = 1_000_000
path_training_data = "data/training_ephems/test_set_bang_bang"
num_ephems = 100_000
ephem_version = 1.0
ephem_step_size = 1
mass_penalty = 100.0
tof_scale = 1.0
pretrain_gradient_steps = 1_000
batch_size = 256
pt_log_interval = 1_000
t_log_interval = 1_000
loss_report_rate = 10
save_replay_buffer = true
read_replay_buffer = false
path_replay_buffer = "z_script_output/replay_buffers/tbt/replay_buffer.pkl"
flag_gen_H_traj = true
seed_traj = 48
flag_report_live = true
eps_final = 0.0001
init_costate_guesses = 100
root_max_iters = 10_000
timeout_per_trajectory = 600
gamma = 0.5
flag_debug_h_targeter = false
checkpoint_freq = 50_000
nn_arch_type = "custom"
load_model_checkpoint = false
learning_rate = 0.0003